[package]
name = "salvo"
version = "0.8.0"
authors = [ "Chrislearn Young <chrislearn@hotmail.com>" ]
edition = "2018"
description = """
A simple web framework
"""
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = [ "salvo", "web", "framework", "server" ]
license = "MIT OR Apache-2.0"
categories = [ "web-programming::http-server" ]
autoexamples = true

[package.metadata.docs.rs]
all-features = true

[badges]
codecov = { repository = "salvo-rs/salvo", branch = "master", service = "github" }

[lib]
name = "salvo"
path = "src/lib.rs"

[features]
default = []
full = [ "extra", "tls", "anyhow" ]
tls = [ "salvo_core/tls" ]
extra = [ "salvo_extra" ]
anyhow = [ "salvo_core/anyhow" ]

[profile.dev]
codegen-units = 4

[workspace]
members = [
  ".",
  "core",
  "extra",
  "macros",
]

[dependencies]
async-trait = "0.1.42"
salvo_core = { version = "0.8.0", default-features = false }
salvo_extra = {version = "0.8.0", default-features = false, optional = true }

[dev-dependencies]
futures = { version = "0.3", features = [ "std" ] }
once_cell = "1"
reqwest = "0.11"
serde = "1"
serde_derive = "1"
salvo_core = {  version = "0.8", features = ["full"] }
salvo_extra = "0.8"
salvo_macros = "0.6"
tokio = { version = "1", features = [ "full" ] }
tokio-stream = { version = "0.1", features = [ "net" ] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"

[patch.crates-io]
salvo = { path = "." }
salvo_core = { path = "core" }
salvo_macros = { path = "macros" }
salvo_extra = { path = "extra" }
