[package]
name = "salvo_core"
version = "0.10.3"
authors = [ "Chrislearn Young <chrislearn@hotmail.com>" ]
edition = "2018"
description = """
A simple web framework written by rust
"""
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
readme = "../README.md"
keywords = [ "salvo", "web", "framework", "server" ]
license = "MIT OR Apache-2.0"
categories = [ "web-programming::http-server" ]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
full = ["tls", "anyhow"]
tls = ["tokio-rustls"]

[dependencies]
anyhow = {version = "1", optional = true }
async-trait = "0.1"
base64 = "0.13"
bitflags = "1"
bytes = "1"
cookie = { version = "0.14", features = [ "percent-encode" ] }
display_bytes = "0.2"
double-checked-cell-async = "2"
form_urlencoded = "1"
futures = { version = "0.3", features = [ "std" ] }
futures-util = "0.3"
headers = "0.3"
http = "0.2"
httparse = "1"
hyper = { version = "0.14", features = ["stream", "server", "http1", "http2", "tcp", "client"] }
mime = "0.3"
mime_guess = "2"
multimap = { version = "0.8", features = [ "serde" ] }
num_cpus = "1"
once_cell = "1"
percent-encoding = "2"
pin-utils = "0.1"
rand = "0.8"
regex = "1"
salvo_macros = { version = "0.10", path="../macros"}
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tempdir = "0.3"
textnonce = "1"
thiserror = "1"
time = "0.2"
tokio = { version = "1", features = [ "full" ] }
tokio-rustls = { version = "0.22", optional = true }
tracing = "0.1"
tracing-futures= "0.2"
twoway = "0.2"

[dev-dependencies]
futures-test = "0.3"
